```{r}
library(tidyverse)
library(cowplot)
library(cat.extras)
library(ggsignif)
library(here)
theme_sedseq <- function(base_size=10) {
  theme_grey(base_size=base_size, base_family = "") %+replace%
    theme(panel.grid=element_blank(),
          axis.text = element_text(size = base_size),
          strip.text.x = element_text(size = base_size, margin = margin(t = 10)),
          strip.text.y = element_text(size = base_size, margin = margin(r = 10)),
          panel.background=element_blank(),
          axis.ticks=element_line(colour="grey20"),
          panel.border=element_rect(fill=NA),
          legend.background = element_blank(),
          legend.key.height = unit(3, "mm"),
          legend.key = element_blank(),
          strip.background = element_blank(),
          legend.box.spacing = unit(1, "mm"))
}
theme_set(theme_sedseq(base_size=10))

stress.cols <-  c("30C"="#7F7F7F",
                  "42C"=RColorBrewer::brewer.pal(n=7,"Oranges")[4],
                  "46C"=RColorBrewer::brewer.pal(n=7,"Oranges")[6],
                  "mock"="#7F7F7F",
                  "Azide 0.5%"=RColorBrewer::brewer.pal(n=5,"Greens")[3],
                  "Azide 0.8%"=RColorBrewer::brewer.pal(n=5,"Greens")[5],
                  "Ethanol 5%"=RColorBrewer::brewer.pal(n=7,"Purples")[3],
                  "Ethanol 7.5%"=RColorBrewer::brewer.pal(n=7,"Purples")[5],
                  "Ethanol 10%"=RColorBrewer::brewer.pal(n=7,"Purples")[6],
                  "Ethanol 15%"=RColorBrewer::brewer.pal(n=7,"Purples")[7])
```

```{r}
github_dir <- here()
df_rna <- read_tsv(file.path(github_dir,"data_processed/231023_thresh400_analyze_smFISH_RNA.tsv.gz")) %>%
  mutate(Date=as.character(Date)) %>%
  mutate(Condition=str_replace(Condition,"yJB01_",""),
         Condition=factor(Condition,levels=c("30C","42C","46C")),
         Date=if_else(Date%in%c("20230823","20230825"),"230823/5",
                      if_else(Date=="20230810","230810",
                              if_else(Date=="20230816","230816",Date))),
         Date=factor(Date,levels=c("230810","230816","230823/5")))
df_random <- read_tsv(file.path(github_dir,"data_processed/231023_thresh400_analyze_smFISH_random.tsv.gz")) %>%
  mutate(Date=as.character(Date)) %>%
  mutate(Condition=str_replace(Condition,"yJB01_",""),
         Condition=factor(Condition,levels=c("30C","42C","46C")),
         Date=if_else(Date%in%c("20230823","20230825"),"230823/5",
                      if_else(Date=="20230810","230810",
                              if_else(Date=="20230816","230816",Date))),
         Date=factor(Date,levels=c("230810","230816","230823/5")))

df_random_stats <- df_random %>%
  group_by(Date,Transcript,Condition,Image_id,Cell_id,Zidx,Key,Channel) %>%
  summarise(signal.mean = mean(ROI_mean),
            signal.sd = sd(ROI_mean,na.rm=T))

df_Z <- df_rna %>%
  filter(!is.na(Cell_id)) %>%
  group_by(Date,Transcript,Condition,Image_id,Cell_id,Zidx,Channel) %>%
  summarise(mean_intensity = mean(ROI_mean)) %>%
  left_join(df_random_stats, by=c("Date","Transcript","Condition","Image_id","Cell_id","Zidx","Channel")) %>%
  mutate(Zscore = (mean_intensity-signal.mean)/signal.sd)%>%
  unite(Sample,Transcript,Date,Condition,remove=F,sep="~") %>%
  group_by(Sample,Date,Transcript,Condition,Image_id,Cell_id,Channel) %>%
  summarise(Zscore = mean(Zscore))

ymin <- (-2.25)
ymax <- 2.5
df <- df_Z %>%
  filter(Date=="230823/5",
         Channel=="PAB1") %>%
  mutate(Transcript=factor(Transcript,levels=c("SSB1","ADD66","SSA4","HSP104")),
         Condition=factor(Condition,levels=c("30C","46C"))) %>%
  mutate(Zscore_filt = if_else(Zscore<ymin,ymin,
                             if_else(Zscore>ymax,ymax,Zscore))) %>%
  arrange(Transcript,Condition)
df_sum <- df %>%
  group_by(Condition,Transcript) %>%
  summarise(mean = mean(Zscore),
    sd = sd(Zscore, na.rm = TRUE),
    n = n(),
    sem = sd / sqrt(n)) %>%
  arrange(Transcript,Condition)


dodge_width <- 0.5
p_points_mean <- ggplot(df,
       aes(x=Transcript,y=Zscore_filt,group=interaction(Transcript,Condition)))+
   geom_hline(yintercept = 0, linetype = "dashed", size = 0.3)+
  geom_point(aes(color=Condition),
             shape=16,alpha=0.3,position=position_jitterdodge(jitter.width=0.2,dodge.width = 0.8), size = 0.3)+
  #geom_col(data = df_sum, aes(x = Transcript, y = mean, fill = Condition), position=position_dodge(dodge_width), color = "black")+
  #geom_boxplot(aes(fill = Condition), alpha = 0.6, draw_quantiles = c(0.5),position=position_dodge(0.8), size = 0.3, outliers = FALSE)+
  geom_errorbar(data=df_sum,color="black",size=0.5,
                aes(ymin=mean,y=mean,ymax=mean),
                width=0.3, position=position_dodge(0.8))+
  geom_errorbar(data=df_sum,
    aes(ymin = mean - sem, y=mean, ymax = mean + sem),
  width = 0,size=0.5, position=position_dodge(0.8)
  ) +

  scale_fill_manual(values=stress.cols)+
  scale_color_manual(values=stress.cols)+
 #facet_grid(.~Transcript)+
  coord_cartesian(ylim=c(-1.75,2.1),xlim=c(0.5,4.5),expand=F)+
  labs(x="",y="")+
  theme(legend.position = 'none',
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
p_points_mean

p_mean <- ggplot(df_sum,
                 aes(x=Transcript,y=mean))+
  geom_errorbar(aes(color=Condition,ymin=mean-sem,y=mean,ymax=mean+sem),
                width=0)+
  geom_point(aes(color=Condition), size = 1)+
  geom_errorbar(data=df_sum,
                aes(ymin=mean,y=mean,ymax=mean, color = Condition),
                width=0.3)+
  scale_color_manual(values=stress.cols)+
  labs(x="",y="")+
  coord_cartesian(ylim=c(-0.1,0.75))+
  scale_y_continuous(breaks=c(0,0.6))+
  theme(legend.position='none',
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank())
p_mean
```

```{r}

p_mean_46 <- ggplot(df_sum_46,
                 aes(x=Transcript,y=mean))+
  geom_col(aes(fill=Transcript), color = "black")+
  geom_errorbar(aes(fill=Transcript,ymin=mean-sem,y=mean,ymax=mean+sem),
                width=0.1)+
  scale_color_manual(values=stress.cols)+
  labs(y="Colocalization score (46°C)",y="Probe")+
  coord_cartesian(ylim=c(0,0.75))+
  scale_y_continuous(breaks=c(0,0.6))
  #theme(legend.position='none',
        #axis.text.x = element_blank(),
        #axis.ticks.x = element_blank())
p_mean_46

ggsave(file.path(github_dir,"figures","Figure2","smFISH_Zscore_points.pdf"),
        egg::set_panel_size(p=p_points_mean,
                            width=unit(100,"mm"),height=unit(30,"mm")),
       width=150,height=100,units="mm",bg = "transparent")
ggsave(file.path(github_dir,"figures","Figure2","smFISH_Zscore_diff.pdf"),
        egg::set_panel_size(p=p_mean,
                            width=unit(50,"mm"),height=unit(28,"mm")),
       width=80,height=40,units="mm",bg = "transparent")
```
```{r}
# Pivot mean values
df_mean_wide <- df_sum %>%
  select(Transcript, Condition, mean) %>%
  pivot_wider(names_from = Condition, values_from = mean)

# Pivot sem values
df_sem_wide <- df_sum %>%
  select(Transcript, Condition, sem) %>%
  pivot_wider(names_from = Condition, values_from = sem)

df_diff <- df_mean_wide %>%
  left_join(df_sem_wide, by = "Transcript", suffix = c("_mean", "_sem")) %>%
  mutate(
    diff = `46C_mean` - `30C_mean`,
    sem_diff = sqrt(`30C_sem`^2 + `46C_sem`^2)
  )

df_diff <- df_diff %>%
  mutate(
    t_stat = diff / sem_diff,
    p_value = 2 * pt(-abs(t_stat), df = Inf),  # assume large n
    lower_CI = diff - 1.96 * sem_diff,
    upper_CI = diff + 1.96 * sem_diff
  )

ggplot(df_diff, aes(x = Transcript, y = diff, fill = Transcript)) +
  geom_col(color = "black", width = 0.7) +
  geom_errorbar(aes(ymin = diff - sem_diff, ymax = diff + sem_diff), 
                width = 0.2, color = "black") +
  labs(
    x = "Transcript (Probe)",
    y = "Δ Colocalization score \n(46°C − 30°C)",
   # title = "Difference in Colocalization score between 46°C and 30°C"
  ) 
```

```{r}

df_46 <- df %>% filter(Condition == "46C")

pairwise.t.test(x=df_46$Zscore, g=df_46$Transcript, p.adjust.method = "holm")

pw_46 <- pairwise.t.test(x = df_46$Zscore, g = df_46$Transcript, p.adjust.method = "holm")

# Convert matrix to long data frame
pvals_df <- as.data.frame(as.table(pw_46$p.value)) %>%
  filter(!is.na(Freq)) %>%
  rename(group1 = Var1, group2 = Var2, p.adj = Freq)

pvals_df <- pvals_df %>%
  arrange(-p.adj) %>%  # optional: order by p-value so stars stack nicely
  mutate(
    # assign increasing y positions spaced by 0.05 starting at 0.8
    y.position = 0.68 + 0.05 * (row_number() - 1),
    p.signif = case_when(
      p.adj <= 0.001 ~ "***",
      p.adj <= 0.01 ~ "**",
      p.adj <= 0.05 ~ "*",
      TRUE ~ "ns"
    )) %>% 
  filter(group1 != "ADD66" | group2 != "SSB1")

p_mean_46_stats <-ggplot(df_sum_46, aes(x = Transcript, y = mean)) +
  geom_col(aes(fill = Condition), color = "black") +
  geom_errorbar(aes(fill=Transcript,ymin=mean-sem,y=mean,ymax=mean+sem),
                width=0.1)+
  stat_pvalue_manual(
    pvals_df,
    label = "p.signif",
    y.position = "y.position",
    tip.length = 0.01, size = 4
  ) +
  ylab("Colocalization score (46°C)")+
  theme(legend.position = "none")+
  scale_fill_manual(values = stress.cols)

p_mean_46_stats

ggsave(file.path(github_dir,"figures","Figure2","smFISH_Zscore_points_stats.pdf"),
        egg::set_panel_size(p=p_mean_46_stats,
                            width=unit(120,"mm"),height=unit(40,"mm")),
       width=150,height=100,units="mm",bg = "transparent")
```

