---
title: "201202_calculate_TE"
author: "Jared Bard"
date: "10/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(stringsAsFactors=FALSE)  # load character strings as strings
library(tidyverse)
library(cat.extras)
library(cowplot)
```
# colors
```{r}
graycol <- "#333333cc"
orangecol <- "#cc5500cc"
bluecol <- "#0000aacc"
greencol <- "#22cc00cc"
purplecol <- "#cc22cccc"
cyancol <- "#2aa198cc"
redcol <- "#dc322fcc"
violetcol <- "#6c71c4cc"
condition.cols <- c("25C.control"="black","37C.10min"="#998ec3","37C.30min"="#5e3c99","42C.10min"="#fdb863","42C.30min"="#e66101")
label.cols <- c("ribosomal"=bluecol,
                "ribosome biogenesis"=cyancol,
                "HSF1"="red",
                "glycolytic"=greencol,
                "other HS down"=purplecol,
                "other HS up"=orangecol,
                "other"="grey50")
label.levels <- c("HSF1","glycolytic","other HS up",
                  "ribosomal","ribosome biogenesis",
                  "other HS down","other")
```

# input
```{r}
# Read in all data and smoosh together
gene_list <- read_tsv("../../../utility/output/201014_labeled_genes_scer.txt")
ribozero <- read_tsv("src/Weinberg_GSE75897_RiboZero_RPKMs.txt",
                       col_names = c("ORF","RPKM"))
RPF <- read_tsv("src/Weinberg_GSE75897_RPF_RPKMs.txt",col_names = c("ORF","RPF"))

d <- gene_list %>% left_join(ribozero,by=c("ORF")) %>% left_join(RPF,by=c("ORF")) %>%
  mutate(TE=RPF/RPKM)
#write_tsv(d%>%select(ORF,RPF,RPKM,TE),"output/Weinberg_2016_comp_RPKM.tsv")
```
```{r}

low_genes <- c("SPO24","YNL190W","PDI1","SRL1","YOR302W","OLI1","PMP1","PMP2","HAC1","FET3","NCW2","NCP1",
               "EGT2","DSE4","TCB3","INA1","NPC2","FIT3","SML1","UTH1","RTN1","BSC1","SAG1")
y <- d

ggplot(d,aes(RPKM,TE))+
  geom_point(data=y%>%filter(gene%!in%low_genes),alpha=0.3)+
  geom_point(data=y%>%filter(gene%in%low_genes),size=2,color="red")+
  scale_x_log10nice()+
  scale_y_log2nice()
```

